[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
xai_solana_program = "65tLehMbGRJUYJDNP5V2nCy3oVRBQW315gtLxuCSJ88b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jia/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
